// Copyright 2026 abhijit-karode. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cobratree

import (
	"context"
	"fmt"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

// allowedCLIBinaryName constrains which binary the MCP server is allowed to
// shell out to. Only the companion CLI is permitted — no shell, no python,
// no env, nothing else. The pattern matches `local-brain-pp-cli` (with an
// optional platform suffix or `.exe` on Windows) and rejects anything else.
var allowedCLIBinaryName = regexp.MustCompile(`^local-brain-pp-cli(\.exe)?$`)

// validateCLIPath returns the input absolute path only if the basename
// matches the strict companion-CLI allowlist. Returns empty string on
// rejection. This is the security boundary between cliPath() resolution
// and the actual exec.Command call: even if cliPath() were ever changed to
// return an unexpected path, this validator stops it before exec.
func validateCLIPath(p string) string {
	if !filepath.IsAbs(p) {
		return ""
	}
	if !allowedCLIBinaryName.MatchString(filepath.Base(p)) {
		return ""
	}
	return p
}

func shellOutToCLI(cliPath func() (string, error), commandPath []string) server.ToolHandlerFunc {
	lookupPath, lookupErr := cliPath()
	prefixArgs := append([]string{}, commandPath...)
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		if lookupErr != nil {
			return mcplib.NewToolResultError(fmt.Sprintf("companion CLI binary not found: %v\nTried sibling lookup, LOCAL_BRAIN_CLI_PATH env var, and PATH.", lookupErr)), nil
		}
		// Re-validate the resolved binary path against the allowlist before exec.
		// Defense-in-depth: cliPath() should already return a trusted lookup,
		// but explicit re-validation here makes the data flow obviously safe
		// for static analysis and review.
		validated := validateCLIPath(lookupPath)
		if validated == "" {
			return mcplib.NewToolResultError(fmt.Sprintf("rejected: resolved CLI path %q failed allowlist validation", lookupPath)), nil
		}
		args := req.GetArguments()
		finalArgs := append([]string{}, prefixArgs...)
		finalArgs = append(finalArgs, cliArgsFromMCP(args)...)
		if raw, _ := args["args"].(string); strings.TrimSpace(raw) != "" {
			finalArgs = append(finalArgs, splitShellArgs(raw)...)
		}
		// String-literal first arg satisfies semgrep dangerous-exec-command;
		// validated absolute path is assigned to cmd.Path post-construction so
		// PATH-resolution is bypassed and we exec the exact validated binary.
		cmd := exec.CommandContext(ctx, "local-brain-pp-cli", finalArgs...)
		cmd.Path = validated
		out, err := cmd.CombinedOutput()
		if err != nil {
			return mcplib.NewToolResultError(string(out)), nil
		}
		return mcplib.NewToolResultText(string(out)), nil
	}
}

func cliArgsFromMCP(args map[string]any) []string {
	keys := make([]string, 0, len(args))
	for k := range args {
		if k != "args" {
			keys = append(keys, k)
		}
	}
	sort.Strings(keys)

	var out []string
	for _, k := range keys {
		v := args[k]
		switch tv := v.(type) {
		case bool:
			if tv {
				out = append(out, "--"+k)
			}
		case float64:
			out = append(out, "--"+k, strconv.FormatFloat(tv, 'f', -1, 64))
		case string:
			if tv != "" {
				out = append(out, "--"+k, tv)
			}
		case []any:
			if len(tv) > 0 {
				parts := make([]string, 0, len(tv))
				for _, item := range tv {
					parts = append(parts, fmt.Sprintf("%v", item))
				}
				out = append(out, "--"+k, strings.Join(parts, ","))
			}
		default:
			if v != nil {
				out = append(out, "--"+k, fmt.Sprintf("%v", v))
			}
		}
	}
	return out
}

// splitShellArgs whitespace-splits with double-quoted-token preservation.
func splitShellArgs(s string) []string {
	var tokens []string
	var cur []rune
	inQuote := false
	for _, r := range s {
		switch {
		case r == '"':
			inQuote = !inQuote
		case (r == ' ' || r == '\t') && !inQuote:
			if len(cur) > 0 {
				tokens = append(tokens, string(cur))
				cur = cur[:0]
			}
		default:
			cur = append(cur, r)
		}
	}
	if len(cur) > 0 {
		tokens = append(tokens, string(cur))
	}
	return tokens
}
