// Copyright 2026 abhijit-karode. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"local-brain-pp-cli/internal/cli"
	"local-brain-pp-cli/internal/client"
	"local-brain-pp-cli/internal/config"
	"local-brain-pp-cli/internal/mcp/cobratree"
	"local-brain-pp-cli/internal/store"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("custom_automation_create",
			mcplib.WithDescription("Create a new custom automation (writes run.sh + plist/cron entry). Required: name, prompt. Optional: schedule, agent, deliveryEmail (plus 2 more). Returns the new CustomAutomation."),
			mcplib.WithString("name", mcplib.Required(), mcplib.Description("Human-readable name (will be slugified to id)")),
			mcplib.WithString("prompt", mcplib.Required(), mcplib.Description("Agent CLI prompt to execute on schedule (use --editor for long prompts)")),
			mcplib.WithString("schedule", mcplib.Description("Schedule spec — daily@08:00, weekly@monday-09:00, hourly@:30, every-15m, or a raw cron expression")),
			mcplib.WithString("agent", mcplib.Description("Agent name to invoke via LB_AGENT_CLI (defaults to LB_AGENT_NAME env or empty)")),
			mcplib.WithString("deliveryEmail", mcplib.Description("Append 'email the results' to the prompt")),
			mcplib.WithString("deliverySlack", mcplib.Description("Append 'send results via Slack DM' to the prompt")),
			mcplib.WithString("deliveryWorkspace", mcplib.Description("Save outputs to ~/Documents/neo-workspace (default true)")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/automation/custom", []mcpParamBinding{{PublicName: "name", WireName: "name", Location: "body"},{PublicName: "prompt", WireName: "prompt", Location: "body"},{PublicName: "schedule", WireName: "schedule", Location: "body"},{PublicName: "agent", WireName: "agent", Location: "body"},{PublicName: "deliveryEmail", WireName: "deliveryEmail", Location: "body"},{PublicName: "deliverySlack", WireName: "deliverySlack", Location: "body"},{PublicName: "deliveryWorkspace", WireName: "deliveryWorkspace", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("custom_automation_delete",
			mcplib.WithDescription("Delete a custom automation (removes plist/cron + dir). Required: id. Optional: keepLogs. Returns the DeleteResult. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Automation id")),
			mcplib.WithString("keepLogs", mcplib.Description("Preserve the log directory")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/automation/custom/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"},{PublicName: "keepLogs", WireName: "keepLogs", Location: "query"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("custom_automation_list",
			mcplib.WithDescription("List all custom automations with status. Optional: enabledOnly, filter. Returns array of CustomAutomation."),
			mcplib.WithString("enabledOnly", mcplib.Description("Show only enabled automations")),
			mcplib.WithString("filter", mcplib.Description("Substring filter on name")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/automation/custom", []mcpParamBinding{{PublicName: "enabledOnly", WireName: "enabledOnly", Location: "query"},{PublicName: "filter", WireName: "filter", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("custom_automation_logs",
			mcplib.WithDescription("Tail logs for a custom automation. Required: id. Optional: tail, follow. Returns the LogResult."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Automation id")),
			mcplib.WithString("tail", mcplib.Description("Lines to tail")),
			mcplib.WithString("follow", mcplib.Description("Follow")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/automation/custom/{id}/logs", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"},{PublicName: "tail", WireName: "tail", Location: "query"},{PublicName: "follow", WireName: "follow", Location: "query"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("custom_automation_run_now",
			mcplib.WithDescription("Trigger a custom automation immediately. Required: id. Optional: wait. Returns the new AutomationRunResult."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Automation id")),
			mcplib.WithString("wait", mcplib.Description("Block until completion")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/automation/custom/{id}/run-now", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"},{PublicName: "wait", WireName: "wait", Location: "query"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("custom_automation_state",
			mcplib.WithDescription("Get the parsed JSON state from this automation's last run (continuity for next fire). Required: id. Returns the AutomationState."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Automation id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/automation/custom/{id}/state", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("custom_automation_update",
			mcplib.WithDescription("Update an existing custom automation. Required: id. Optional: prompt, schedule, enabled (plus 1 more). Returns the new CustomAutomation."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Automation id (slug)")),
			mcplib.WithString("prompt", mcplib.Description("New prompt")),
			mcplib.WithString("schedule", mcplib.Description("New schedule spec")),
			mcplib.WithString("enabled", mcplib.Description("Enable or disable")),
			mcplib.WithString("agent", mcplib.Description("Agent name (passed to LB_AGENT_CLI)")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/automation/custom/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"},{PublicName: "prompt", WireName: "prompt", Location: "body"},{PublicName: "schedule", WireName: "schedule", Location: "body"},{PublicName: "enabled", WireName: "enabled", Location: "body"},{PublicName: "agent", WireName: "agent", Location: "body"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("embeddings_backfill",
			mcplib.WithDescription("Generate embeddings for memories that don't have them yet (shells to vendored Python). Optional: namespace, batchSize, all. Returns the new BackfillResult."),
			mcplib.WithString("namespace", mcplib.Description("Specific namespace (omit for all)")),
			mcplib.WithString("batchSize", mcplib.Description("Memories per namespace per run (default 50)")),
			mcplib.WithString("all", mcplib.Description("Process all namespaces")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/embeddings/backfill", []mcpParamBinding{{PublicName: "namespace", WireName: "namespace", Location: "body"},{PublicName: "batchSize", WireName: "batchSize", Location: "body"},{PublicName: "all", WireName: "all", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("embeddings_check_deps",
			mcplib.WithDescription("Probe candidate Python interpreters for sqlite-vec + sentence-transformers. Returns the DepsCheck."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/embeddings/check-deps", []mcpParamBinding{ }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("embeddings_heal_shadow_tables",
			mcplib.WithDescription("Drop orphaned sqlite-vec shadow tables left by a crashed backfill (transcendence). Optional: namespace, all, dryRun. Returns the new HealResult."),
			mcplib.WithString("namespace", mcplib.Description("Specific namespace (omit with --all for every namespace)")),
			mcplib.WithString("all", mcplib.Description("Heal every namespace")),
			mcplib.WithString("dryRun", mcplib.Description("Show what would be dropped without actually dropping")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/embeddings/heal-shadow-tables", []mcpParamBinding{{PublicName: "namespace", WireName: "namespace", Location: "body"},{PublicName: "all", WireName: "all", Location: "body"},{PublicName: "dryRun", WireName: "dryRun", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("embeddings_rebuild",
			mcplib.WithDescription("Drop and regenerate ALL embeddings for a namespace (use after embedding model change). Required: namespace. Optional: yes. Returns the new RebuildResult."),
			mcplib.WithString("namespace", mcplib.Required(), mcplib.Description("Namespace to rebuild")),
			mcplib.WithString("yes", mcplib.Description("Confirm destructive operation")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/embeddings/rebuild", []mcpParamBinding{{PublicName: "namespace", WireName: "namespace", Location: "body"},{PublicName: "yes", WireName: "yes", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("embeddings_status",
			mcplib.WithDescription("Per-namespace embedding coverage — % embedded, age of oldest unembedded (transcendence). Optional: namespace. Returns array of EmbeddingStatus."),
			mcplib.WithString("namespace", mcplib.Description("Specific namespace (or prefix glob)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/embeddings/status", []mcpParamBinding{{PublicName: "namespace", WireName: "namespace", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("index_rebuild",
			mcplib.WithDescription("Rebuild ~/.local-brain/global/INDEX.md from current namespace stats. Returns the new IndexResult."),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/index/rebuild", []mcpParamBinding{ }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("index_show",
			mcplib.WithDescription("Print the current rendered index (markdown by default). Optional: namespace. Returns the IndexResult."),
			mcplib.WithString("namespace", mcplib.Description("Show only entries for namespaces matching this glob")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/index/show", []mcpParamBinding{{PublicName: "namespace", WireName: "namespace", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("memory_bisect",
			mcplib.WithDescription("Show the atomic memories that were synthesized into a compiled memory (provenance via timestamp/namespace inference) (transcendence). Required: id. Optional: window. Returns the BisectResult."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Compiled memory ID")),
			mcplib.WithString("window", mcplib.Description("Time window before the compiled memory's created_at to scan (default '7d')")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/memory/bisect", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "query"},{PublicName: "window", WireName: "window", Location: "query"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("memory_context",
			mcplib.WithDescription("Load all memories for a namespace (alias for list with default limit 50). Required: namespace. Optional: limit. Returns the ContextResult."),
			mcplib.WithString("namespace", mcplib.Required(), mcplib.Description("Namespace to load")),
			mcplib.WithString("limit", mcplib.Description("Max memories to return (default 50)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/memory/context", []mcpParamBinding{{PublicName: "namespace", WireName: "namespace", Location: "query"},{PublicName: "limit", WireName: "limit", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("memory_dedupe",
			mcplib.WithDescription("Find duplicate memories by content hash across namespaces (transcendence). Optional: namespace, apply. Returns array of DupGroup."),
			mcplib.WithString("namespace", mcplib.Description("Limit to a namespace prefix")),
			mcplib.WithString("apply", mcplib.Description("If true, delete duplicates (keep the oldest); else dry-run")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/memory/dedupe", []mcpParamBinding{{PublicName: "namespace", WireName: "namespace", Location: "query"},{PublicName: "apply", WireName: "apply", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("memory_export",
			mcplib.WithDescription("Export memories from a namespace (alias to namespace export). Required: namespace. Optional: format, includeEmbeddings, type. Returns the ExportResult."),
			mcplib.WithString("namespace", mcplib.Required(), mcplib.Description("Namespace to export")),
			mcplib.WithString("format", mcplib.Description("Output format: json, jsonl, markdown, csv (default: json)")),
			mcplib.WithString("includeEmbeddings", mcplib.Description("Include embedding vectors (large; default false)")),
			mcplib.WithString("type", mcplib.Description("Filter by memory type")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/memory/export", []mcpParamBinding{{PublicName: "namespace", WireName: "namespace", Location: "query"},{PublicName: "format", WireName: "format", Location: "query"},{PublicName: "includeEmbeddings", WireName: "includeEmbeddings", Location: "query"},{PublicName: "type", WireName: "type", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("memory_forget",
			mcplib.WithDescription("Delete a memory by ID (also removes its embedding row and regenerates the namespace markdown mirror). Required: id. Optional: namespace. Returns the ForgetResult. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Memory ID to delete")),
			mcplib.WithString("namespace", mcplib.Description("Restrict to a specific namespace (otherwise searches all)")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/memory/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"},{PublicName: "namespace", WireName: "namespace", Location: "query"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("memory_get",
			mcplib.WithDescription("Get a single memory by ID, searching across all namespaces if --namespace not given. Required: id. Optional: namespace. Returns the Memory."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Memory ID (e.g. mem-20260513-180000-abcd1234)")),
			mcplib.WithString("namespace", mcplib.Description("Restrict search to a specific namespace")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/memory/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"},{PublicName: "namespace", WireName: "namespace", Location: "query"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("memory_import",
			mcplib.WithDescription("Import memories from a file (JSON array, JSONL, or markdown). Required: file. Optional: namespace, format, dedupeBy. Returns the new ImportResult."),
			mcplib.WithString("file", mcplib.Required(), mcplib.Description("Path to file to import (use '-' for stdin)")),
			mcplib.WithString("namespace", mcplib.Description("Override target namespace (defaults to memory's own namespace field)")),
			mcplib.WithString("format", mcplib.Description("File format: json, jsonl, markdown (default: auto-detect from extension)")),
			mcplib.WithString("dedupeBy", mcplib.Description("Skip imports whose 'hash' or 'id' already exists (default: hash)")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/memory/import", []mcpParamBinding{{PublicName: "file", WireName: "file", Location: "body"},{PublicName: "namespace", WireName: "namespace", Location: "body"},{PublicName: "format", WireName: "format", Location: "body"},{PublicName: "dedupeBy", WireName: "dedupeBy", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("memory_list",
			mcplib.WithDescription("List memories in a namespace (most recent first). Required: namespace. Optional: limit, type, tag (plus 2 more). Returns array of Memory."),
			mcplib.WithString("namespace", mcplib.Required(), mcplib.Description("Namespace to list")),
			mcplib.WithString("limit", mcplib.Description("Max memories to return (default 50)")),
			mcplib.WithString("type", mcplib.Description("Filter by memory type (comma-separated)")),
			mcplib.WithString("tag", mcplib.Description("Filter by tag (comma-separated, AND-match)")),
			mcplib.WithString("since", mcplib.Description("Only memories created after this time")),
			mcplib.WithString("before", mcplib.Description("Only memories created before this time")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/memory/list", []mcpParamBinding{{PublicName: "namespace", WireName: "namespace", Location: "query"},{PublicName: "limit", WireName: "limit", Location: "query"},{PublicName: "type", WireName: "type", Location: "query"},{PublicName: "tag", WireName: "tag", Location: "query"},{PublicName: "since", WireName: "since", Location: "query"},{PublicName: "before", WireName: "before", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("memory_patterns",
			mcplib.WithDescription("Find tags appearing across multiple namespaces (cross-cutting topics) — exposes the linter's heart on demand (transcendence). Optional: minNamespaces, limit, excludeTag. Returns array of TagPattern."),
			mcplib.WithString("minNamespaces", mcplib.Description("Minimum namespace count for a tag to be reported (default 3)")),
			mcplib.WithString("limit", mcplib.Description("Max patterns to return (default 20)")),
			mcplib.WithString("excludeTag", mcplib.Description("Tags to exclude (comma-separated; default 'compiled,auto-generated')")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/memory/patterns", []mcpParamBinding{{PublicName: "minNamespaces", WireName: "minNamespaces", Location: "query"},{PublicName: "limit", WireName: "limit", Location: "query"},{PublicName: "excludeTag", WireName: "excludeTag", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("memory_save",
			mcplib.WithDescription("Save a memory (insight, decision, outcome, action_item, preference, or compiled) to a namespace. Required: namespace, content. Optional: type, tags, source (plus 1 more). Returns the new SaveMemoryResult."),
			mcplib.WithString("namespace", mcplib.Required(), mcplib.Description("Namespace to save to (e.g. 'accounts/acme', 'global', 'projects/x')")),
			mcplib.WithString("type", mcplib.Description("Memory type — one of: insight, decision, outcome, action_item, preference, compiled (default: insight)")),
			mcplib.WithString("content", mcplib.Required(), mcplib.Description("The memory content (use --editor to open $EDITOR for long-form)")),
			mcplib.WithString("tags", mcplib.Description("Comma-separated tags")),
			mcplib.WithString("source", mcplib.Description("Where this memory came from (e.g. 'meeting 2026-05-13', 'CR-274381507')")),
			mcplib.WithString("rotateTag", mcplib.Description("If set, delete any existing memories in this namespace whose tags contain this rotation key before saving (e.g....")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/memory/save", []mcpParamBinding{{PublicName: "namespace", WireName: "namespace", Location: "body"},{PublicName: "type", WireName: "type", Location: "body"},{PublicName: "content", WireName: "content", Location: "body"},{PublicName: "tags", WireName: "tags", Location: "body"},{PublicName: "source", WireName: "source", Location: "body"},{PublicName: "rotateTag", WireName: "rotateTag", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("memory_search",
			mcplib.WithDescription("Search memories by keyword (FTS5), semantic similarity (sqlite-vec), or hybrid. Required: query. Optional: namespace, mode, limit (plus 5 more). Returns array of MemorySearchResult."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query")),
			mcplib.WithString("namespace", mcplib.Description("Limit search to a specific namespace (or namespace prefix glob like 'accounts/*')")),
			mcplib.WithString("mode", mcplib.Description("Search mode: auto, keyword, semantic, hybrid (default: auto)")),
			mcplib.WithString("limit", mcplib.Description("Max results (default 20)")),
			mcplib.WithString("type", mcplib.Description("Filter by memory type (comma-separated for multiple)")),
			mcplib.WithString("tag", mcplib.Description("Filter by tag (comma-separated; AND-match)")),
			mcplib.WithString("since", mcplib.Description("Only memories created after this time (e.g. '2h', '24h', '7d', '2026-01-01')")),
			mcplib.WithString("before", mcplib.Description("Only memories created before this time")),
			mcplib.WithString("threshold", mcplib.Description("Distance threshold for semantic mode (lower = stricter; default 1.0)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/memory/search", []mcpParamBinding{{PublicName: "query", WireName: "query", Location: "query"},{PublicName: "namespace", WireName: "namespace", Location: "query"},{PublicName: "mode", WireName: "mode", Location: "query"},{PublicName: "limit", WireName: "limit", Location: "query"},{PublicName: "type", WireName: "type", Location: "query"},{PublicName: "tag", WireName: "tag", Location: "query"},{PublicName: "since", WireName: "since", Location: "query"},{PublicName: "before", WireName: "before", Location: "query"},{PublicName: "threshold", WireName: "threshold", Location: "query"}, }, []string{"query", }),
	)
	s.AddTool(
		mcplib.NewTool("memory_stale",
			mcplib.WithDescription("List action_item memories older than N days across every namespace (transcendence). Optional: days, type, namespace (plus 1 more). Returns array of StaleMemory."),
			mcplib.WithString("days", mcplib.Description("Days of age threshold (default 14)")),
			mcplib.WithString("type", mcplib.Description("Memory type to filter (default: action_item)")),
			mcplib.WithString("namespace", mcplib.Description("Limit to a namespace prefix")),
			mcplib.WithString("limit", mcplib.Description("Max results")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/memory/stale", []mcpParamBinding{{PublicName: "days", WireName: "days", Location: "query"},{PublicName: "type", WireName: "type", Location: "query"},{PublicName: "namespace", WireName: "namespace", Location: "query"},{PublicName: "limit", WireName: "limit", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("memory_watch",
			mcplib.WithDescription("Tail new memories as they're written (live mode using fseventfs/inotify) (transcendence). Optional: namespace, type. Returns array of Memory."),
			mcplib.WithString("namespace", mcplib.Description("Namespace to watch")),
			mcplib.WithString("type", mcplib.Description("Filter by memory type")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/memory/watch", []mcpParamBinding{{PublicName: "namespace", WireName: "namespace", Location: "query"},{PublicName: "type", WireName: "type", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("memory_automation_disable",
			mcplib.WithDescription("Uninstall the launchd plist or crontab entry for this automation. Required: name. Returns the new ScheduleDisableResult."),
			mcplib.WithString("name", mcplib.Required(), mcplib.Description("Automation name")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/automation/memory/{name}/disable", []mcpParamBinding{{PublicName: "name", WireName: "name", Location: "path"}, }, []string{"name", }),
	)
	s.AddTool(
		mcplib.NewTool("memory_automation_enable",
			mcplib.WithDescription("Install the launchd plist (macOS) or crontab entry (Linux/WSL) so this automation runs on its schedule. Required: name. Returns the new ScheduleEnableResult."),
			mcplib.WithString("name", mcplib.Required(), mcplib.Description("Automation name")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/automation/memory/{name}/enable", []mcpParamBinding{{PublicName: "name", WireName: "name", Location: "path"}, }, []string{"name", }),
	)
	s.AddTool(
		mcplib.NewTool("memory_automation_list",
			mcplib.WithDescription("List the 9 memory automations with current status (last-run, next-run, locked, enabled). Returns array of MemoryAutomation."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/automation/memory", []mcpParamBinding{ }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("memory_automation_logs",
			mcplib.WithDescription("Tail logs for a memory automation. Required: name. Optional: tail, since, follow. Returns the LogResult."),
			mcplib.WithString("name", mcplib.Required(), mcplib.Description("Automation name")),
			mcplib.WithString("tail", mcplib.Description("Lines to tail (default 200)")),
			mcplib.WithString("since", mcplib.Description("Show logs since this time (e.g. '24h')")),
			mcplib.WithString("follow", mcplib.Description("Follow log output (-f)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/automation/memory/{name}/logs", []mcpParamBinding{{PublicName: "name", WireName: "name", Location: "path"},{PublicName: "tail", WireName: "tail", Location: "query"},{PublicName: "since", WireName: "since", Location: "query"},{PublicName: "follow", WireName: "follow", Location: "query"}, }, []string{"name", }),
	)
	s.AddTool(
		mcplib.NewTool("memory_automation_run_now",
			mcplib.WithDescription("Trigger a memory automation immediately. Required: name. Optional: namespace, force, wait. Returns the new AutomationRunResult."),
			mcplib.WithString("name", mcplib.Required(), mcplib.Description("Automation name (embedder, indexer, compiler, linter, enricher, pruner, rollup, exporter, migrate-namespaces)")),
			mcplib.WithString("namespace", mcplib.Description("Restrict to a namespace (where the automation supports it)")),
			mcplib.WithString("force", mcplib.Description("Bypass the daily lock file")),
			mcplib.WithString("wait", mcplib.Description("Block until the automation completes (default: spawn in background)")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/automation/memory/{name}/run-now", []mcpParamBinding{{PublicName: "name", WireName: "name", Location: "path"},{PublicName: "namespace", WireName: "namespace", Location: "query"},{PublicName: "force", WireName: "force", Location: "query"},{PublicName: "wait", WireName: "wait", Location: "query"}, }, []string{"name", }),
	)
	s.AddTool(
		mcplib.NewTool("memory_automation_status",
			mcplib.WithDescription("Show last-run timestamp, next-run, locked state, and recent log tail for one automation. Required: name. Returns the AutomationStatus."),
			mcplib.WithString("name", mcplib.Required(), mcplib.Description("Automation name")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/automation/memory/{name}/status", []mcpParamBinding{{PublicName: "name", WireName: "name", Location: "path"}, }, []string{"name", }),
	)
	s.AddTool(
		mcplib.NewTool("namespace_backup",
			mcplib.WithDescription("Backup a namespace (or all) to a tar.gz archive containing db + markdown + embeddings. Optional: namespace, dest, all. Returns the new BackupResult."),
			mcplib.WithString("namespace", mcplib.Description("Specific namespace (omit with --all for full brain backup)")),
			mcplib.WithString("dest", mcplib.Description("Destination directory or .tar.gz path")),
			mcplib.WithString("all", mcplib.Description("Backup every namespace")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/namespace/backup", []mcpParamBinding{{PublicName: "namespace", WireName: "namespace", Location: "body"},{PublicName: "dest", WireName: "dest", Location: "body"},{PublicName: "all", WireName: "all", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("namespace_delete",
			mcplib.WithDescription("Delete an entire namespace (db, markdown, embeddings — irreversible). Required: namespace. Returns the DeleteResult. Destructive."),
			mcplib.WithString("namespace", mcplib.Required(), mcplib.Description("Namespace to delete")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/namespace/delete", []mcpParamBinding{{PublicName: "namespace", WireName: "namespace", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("namespace_diff",
			mcplib.WithDescription("Show what changed in a namespace since a given time (transcendence). Required: namespace. Optional: since. Returns the NamespaceDiff."),
			mcplib.WithString("namespace", mcplib.Required(), mcplib.Description("Namespace to diff")),
			mcplib.WithString("since", mcplib.Description("Window start (default '7d')")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/namespace/diff", []mcpParamBinding{{PublicName: "namespace", WireName: "namespace", Location: "query"},{PublicName: "since", WireName: "since", Location: "query"}, }, []string{"namespace", }),
	)
	s.AddTool(
		mcplib.NewTool("namespace_list",
			mcplib.WithDescription("List all namespaces with memory counts. Optional: filter. Returns array of NamespaceInfo."),
			mcplib.WithString("filter", mcplib.Description("Glob filter (e.g. 'accounts/*')")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/namespace/list", []mcpParamBinding{{PublicName: "filter", WireName: "filter", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("namespace_move",
			mcplib.WithDescription("Move memories from one namespace to another (preserving IDs and metadata). Required: from, to. Optional: type. Returns the new MoveResult."),
			mcplib.WithString("from", mcplib.Required(), mcplib.Description("Source namespace")),
			mcplib.WithString("to", mcplib.Required(), mcplib.Description("Target namespace")),
			mcplib.WithString("type", mcplib.Description("Only move memories of this type")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/namespace/move", []mcpParamBinding{{PublicName: "from", WireName: "from", Location: "body"},{PublicName: "to", WireName: "to", Location: "body"},{PublicName: "type", WireName: "type", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("namespace_rename",
			mcplib.WithDescription("Rename a namespace (moves the directory; updates markdown header). Required: from, to. Returns the new RenameResult."),
			mcplib.WithString("from", mcplib.Required(), mcplib.Description("Source namespace")),
			mcplib.WithString("to", mcplib.Required(), mcplib.Description("Target namespace")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/namespace/rename", []mcpParamBinding{{PublicName: "from", WireName: "from", Location: "body"},{PublicName: "to", WireName: "to", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("namespace_restore",
			mcplib.WithDescription("Restore a namespace from a tar.gz archive. Required: archive. Optional: renameTo, merge. Returns the new RestoreResult."),
			mcplib.WithString("archive", mcplib.Required(), mcplib.Description("Path to .tar.gz archive")),
			mcplib.WithString("renameTo", mcplib.Description("Restore under a different namespace name")),
			mcplib.WithString("merge", mcplib.Description("Merge with existing namespace instead of failing if it exists")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/namespace/restore", []mcpParamBinding{{PublicName: "archive", WireName: "archive", Location: "body"},{PublicName: "renameTo", WireName: "renameTo", Location: "body"},{PublicName: "merge", WireName: "merge", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("namespace_stats",
			mcplib.WithDescription("Health stats for namespaces — counts by type, staleness, compilation status, unembedded count. Optional: namespace, staleDays. Returns array of NamespaceStats."),
			mcplib.WithString("namespace", mcplib.Description("Specific namespace (or prefix glob); defaults to all")),
			mcplib.WithString("staleDays", mcplib.Description("Days threshold for stale action items (default 14)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/namespace/stats", []mcpParamBinding{{PublicName: "namespace", WireName: "namespace", Location: "query"},{PublicName: "staleDays", WireName: "staleDays", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("namespace_vacuum",
			mcplib.WithDescription("Compact (VACUUM) the SQLite database for one or all namespaces; reports bytes saved. Optional: namespace, all. Returns the new VacuumResult."),
			mcplib.WithString("namespace", mcplib.Description("Specific namespace (omit for all)")),
			mcplib.WithString("all", mcplib.Description("Vacuum every namespace")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/namespace/vacuum", []mcpParamBinding{{PublicName: "namespace", WireName: "namespace", Location: "body"},{PublicName: "all", WireName: "all", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("schedule_install",
			mcplib.WithDescription("Idempotently install the schedule for a memory or custom automation. Required: type, name. Returns the new ScheduleEnableResult."),
			mcplib.WithString("type", mcplib.Required(), mcplib.Description("Automation type (memory|custom)")),
			mcplib.WithString("name", mcplib.Required(), mcplib.Description("Automation name or id")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/schedule/install", []mcpParamBinding{{PublicName: "type", WireName: "type", Location: "body"},{PublicName: "name", WireName: "name", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("schedule_list",
			mcplib.WithDescription("List all schedule entries (memory + custom automations) across launchd and cron. Optional: type, enabledOnly. Returns array of ScheduleEntry."),
			mcplib.WithString("type", mcplib.Description("Filter by automation type (memory|custom)")),
			mcplib.WithString("enabledOnly", mcplib.Description("Show only enabled entries")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/schedule", []mcpParamBinding{{PublicName: "type", WireName: "type", Location: "query"},{PublicName: "enabledOnly", WireName: "enabledOnly", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("schedule_next_runs",
			mcplib.WithDescription("Show the next N hours of automation fires across launchd + cron in chronological order (transcendence). Optional: hours. Returns array of NextRun."),
			mcplib.WithString("hours", mcplib.Description("Window length in hours (default 24)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/schedule/next-runs", []mcpParamBinding{{PublicName: "hours", WireName: "hours", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("schedule_uninstall",
			mcplib.WithDescription("Remove the schedule for an automation. Required: type, name. Returns the new ScheduleDisableResult."),
			mcplib.WithString("type", mcplib.Required(), mcplib.Description("Automation type")),
			mcplib.WithString("name", mcplib.Required(), mcplib.Description("Automation name or id")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/schedule/uninstall", []mcpParamBinding{{PublicName: "type", WireName: "type", Location: "body"},{PublicName: "name", WireName: "name", Location: "body"}, }, []string{ }),
	)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Tables match resource names.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			data, err = c.Get(path, params)
		case "POST":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Post(path, body)
		case "PUT":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Put(path, body)
		case "PATCH":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Patch(path, body)
		case "DELETE":
			data, _, err = c.Delete(path)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + msg +
					"\nhint: check your API credentials." +
					"\n      Run 'local-brain-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + msg +
					"\nhint: this API is configured without credentials; the service may be blocking the request by rate limit, geography, bot protection, or endpoint policy." +
					"\n      Run 'local-brain-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "local-brain-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 30*time.Second, 0)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "local-brain-pp-cli", "data.db")
}
// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate is an allowlist (SELECT or WITH only) applied AFTER stripping the
// leading whitespace, line comments, block comments, and semicolons that
// SQLite itself ignores before parsing. A naive HasPrefix check on a
// keyword blocklist is bypassable by prefixing the dangerous statement with
// "/* x */" or "-- x\n" — TrimSpace strips outer whitespace but does not
// understand SQL comment syntax. Combined with the empirical fact that
// modernc.org/sqlite's mode=ro does NOT block VACUUM INTO (writes a snapshot
// to a new file) or ATTACH DATABASE (opens a separate writable handle),
// such a bypass produces silent exfiltration to an attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	upper := strings.ToUpper(stripLeadingSQLNoise(query))
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, _ := rows.Columns()
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		rows.Scan(ptrs...)
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "local-brain",
		"description": "The CLI for Local Brain — direct SQLite access, all 11 memory automations bundled, MCP server included, every...",
		"archetype":   "generic",
		"tool_count":  46,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion local-brain-pp-cli binary.",
		"resources": []map[string]any{
			{
				"name": "customAutomation",
				"description": "Create, manage, and schedule user-defined automations (agent CLI prompt + cron, configured via LB_AGENT_CLI)",
				"endpoints": []string{"create", "delete", "list", "logs", "runNow", "state", "update",  },
			},
			{
				"name": "embeddings",
				"description": "Manage sqlite-vec embeddings — backfill, coverage, recovery",
				"endpoints": []string{"backfill", "checkDeps", "healShadowTables", "rebuild", "status",  },
				"syncable": true,
				"searchable": true,
			},
			{
				"name": "index",
				"description": "Local Brain index (table-of-contents) operations",
				"endpoints": []string{"rebuild", "show",  },
				"syncable": true,
				"searchable": true,
			},
			{
				"name": "memory",
				"description": "Save, search, recall, and curate typed memories in ~/.local-brain/<namespace>/memories.db",
				"endpoints": []string{"bisect", "context", "dedupe", "export", "forget", "get", "import", "list", "patterns", "save", "search", "stale", "watch",  },
				"syncable": true,
				"searchable": true,
			},
			{
				"name": "memoryAutomation",
				"description": "The 9 bundled memory automations (embedder, indexer, compiler, linter, enricher, pruner, rollup, exporter,...",
				"endpoints": []string{"disable", "enable", "list", "logs", "runNow", "status",  },
			},
			{
				"name": "namespace",
				"description": "Inspect and manage memory namespaces",
				"endpoints": []string{"backup", "delete", "diff", "list", "move", "rename", "restore", "stats", "vacuum",  },
				"syncable": true,
				"searchable": true,
			},
			{
				"name": "schedule",
				"description": "Cross-platform schedule manager — list, install, uninstall, simulate next runs",
				"endpoints": []string{"install", "list", "nextRuns", "uninstall",  },
				"syncable": true,
				"searchable": true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use since for incremental fetches (filter by modification time).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
		// Command-mirror capabilities are exposed through MCP by shelling out
		// to the companion CLI binary.
		"command_mirror_capabilities": []map[string]string{
			{"name": "One-shot brain doctor", "command": "doctor", "description": "Single call returns DB health, sqlite-vec deps, embedding coverage, model cache, automation status, schedule status,...", "rationale": "Spans SQLite + launchd + cron + Python venv probing + log parsing — no other memory tool unifies these surfaces in...", "via": "mcp-command-mirror"},
			{"name": "Cross-namespace SQL", "command": "sql", "description": "Run arbitrary read-only SELECT statements against the union of all memories tables, joined by namespace.", "rationale": "Direct SQLite access from a CLI; the MCP surface is tool-shaped and cannot expose ad-hoc queries.", "via": "mcp-command-mirror"},
			{"name": "Memory dedupe by content hash", "command": "memory dedupe", "description": "Find duplicate memories across namespaces using the existing hash column and optionally merge them.", "rationale": "The hash column on every memory is unused by the MCP. We exploit it for an O(N) dedupe pass.", "via": "mcp-command-mirror"},
			{"name": "Stale action item triage", "command": "memory stale", "description": "List all action_item memories older than N days across every namespace.", "rationale": "The linter computes this weekly and emails it. We expose it on demand so agents can pipe it into a Slack post or...", "via": "mcp-command-mirror"},
			{"name": "Memory bisect", "command": "memory bisect", "description": "Show which atomic memories were synthesized into a given compiled memory by joining timestamps and namespace.", "rationale": "The compiler doesn't record provenance today. We infer it from the time window before the compiled memory's...", "via": "mcp-command-mirror"},
			{"name": "Cross-namespace tag patterns", "command": "memory patterns", "description": "Find tags appearing in 3+ namespaces, which signals cross-cutting topics worth promoting to global insights.", "rationale": "The linter automation outputs this weekly. We expose it interactively so agents can detect themes during a...", "via": "mcp-command-mirror"},
			{"name": "Embedding shadow-table heal", "command": "embeddings heal-shadow-tables", "description": "Drop and recreate the sqlite-vec virtual table when its shadow tables are orphaned after a crashed backfill.", "rationale": "The MCP heals on save only; operators have no recovery hook today.", "via": "mcp-command-mirror"},
			{"name": "Namespace diff", "command": "namespace diff", "description": "Show what changed in a namespace between two timestamps: memories added, by-type counts moved, last-compiled snapshot.", "rationale": "We have created_at on every row; computing diffs is a SQLite query the MCP doesn't expose.", "via": "mcp-command-mirror"},
			{"name": "Schedule next-runs simulator", "command": "schedule next-runs", "description": "Show the next 24 hours of automation fires in chronological order, combining launchd plists and cron entries.", "rationale": "No tool unifies launchd + cron in one view; we parse both and compute the next firings.", "via": "mcp-command-mirror"},
			{"name": "Run any memory automation manually", "command": "automation memory <name> run-now", "description": "Headlessly trigger any of the 9 memory automations (embedder, indexer, compiler, linter, enricher, pruner, rollup,...", "rationale": "Today this requires shelling into an external orchestration tool. We vendor the scripts so they run from any agent CLI.", "via": "mcp-command-mirror"},
		},
		"playbook": []map[string]string{
			{"topic": "One-shot brain doctor", "insight": "Spans SQLite + launchd + cron + Python venv probing + log parsing — no other memory tool unifies these surfaces in one read."},
			{"topic": "Cross-namespace SQL", "insight": "Direct SQLite access from a CLI; the MCP surface is tool-shaped and cannot expose ad-hoc queries."},
			{"topic": "Memory dedupe by content hash", "insight": "The hash column on every memory is unused by the MCP. We exploit it for an O(N) dedupe pass."},
			{"topic": "Stale action item triage", "insight": "The linter computes this weekly and emails it. We expose it on demand so agents can pipe it into a Slack post or daily briefing."},
			{"topic": "Memory bisect", "insight": "The compiler doesn't record provenance today. We infer it from the time window before the compiled memory's created_at within the same namespace."},
			{"topic": "Cross-namespace tag patterns", "insight": "The linter automation outputs this weekly. We expose it interactively so agents can detect themes during a conversation, not just after a cron run."},
			{"topic": "Embedding shadow-table heal", "insight": "The MCP heals on save only; operators have no recovery hook today."},
			{"topic": "Namespace diff", "insight": "We have created_at on every row; computing diffs is a SQLite query the MCP doesn't expose."},
			{"topic": "Schedule next-runs simulator", "insight": "No tool unifies launchd + cron in one view; we parse both and compute the next firings."},
			{"topic": "Run any memory automation manually", "insight": "Today this requires shelling into an external orchestration tool. We vendor the scripts so they run from any agent CLI."},
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
