// Copyright 2026 abhijit-karode. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"


type AutomationRunResult struct {
	Name string `json:"name"`
	Started bool `json:"started"`
	Pid int `json:"pid"`
	LogPath string `json:"log_path"`
}

type AutomationState struct {
	Id string `json:"id"`
	State json.RawMessage `json:"state"`
}

type AutomationStatus struct {
	Name string `json:"name"`
	Enabled bool `json:"enabled"`
	Locked bool `json:"locked"`
	LastRun string `json:"last_run"`
	NextRun string `json:"next_run"`
	LogTail string `json:"log_tail"`
}

type BackfillResult struct {
	TotalEmbedded int `json:"total_embedded"`
	Namespaces json.RawMessage `json:"namespaces"`
}

type BackupResult struct {
	Archive string `json:"archive"`
	Namespaces json.RawMessage `json:"namespaces"`
	Bytes int `json:"bytes"`
}

type BisectResult struct {
	CompiledId string `json:"compiled_id"`
	Namespace string `json:"namespace"`
	Window string `json:"window"`
	SourceAtoms json.RawMessage `json:"source_atoms"`
	Count int `json:"count"`
}

type ContextResult struct {
	Namespace string `json:"namespace"`
	Total int `json:"total"`
	Memories json.RawMessage `json:"memories"`
}

type CustomAutomation struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Prompt string `json:"prompt"`
	Schedule json.RawMessage `json:"schedule"`
	Agent string `json:"agent"`
	Enabled bool `json:"enabled"`
	CreatedAt string `json:"created_at"`
	LastRun string `json:"last_run"`
	NextRun string `json:"next_run"`
	Locked bool `json:"locked"`
}

type DeleteResult struct {
	Namespace string `json:"namespace"`
	Deleted bool `json:"deleted"`
}

type DepsCheck struct {
	PythonBin string `json:"python_bin"`
	SqliteVecAvailable bool `json:"sqlite_vec_available"`
	SentenceTransformersAvailable bool `json:"sentence_transformers_available"`
	CandidatesTried json.RawMessage `json:"candidates_tried"`
}

type DoctorResult struct {
	Ok bool `json:"ok"`
	BrainDirExists bool `json:"brain_dir_exists"`
	BrainDir string `json:"brain_dir"`
	TotalMemories int `json:"total_memories"`
	TotalNamespaces int `json:"total_namespaces"`
	SqliteVecAvailable bool `json:"sqlite_vec_available"`
	ModelCached bool `json:"model_cached"`
	PythonBin string `json:"python_bin"`
	KiroCliPath string `json:"kiro_cli_path"`
	Schedule json.RawMessage `json:"schedule"`
	Automations json.RawMessage `json:"automations"`
	Namespaces json.RawMessage `json:"namespaces"`
	Warnings json.RawMessage `json:"warnings"`
}

type DupGroup struct {
	Hash string `json:"hash"`
	Members json.RawMessage `json:"members"`
	Count int `json:"count"`
}

type EmbeddingStatus struct {
	Namespace string `json:"namespace"`
	Total int `json:"total"`
	Embedded int `json:"embedded"`
	Unembedded int `json:"unembedded"`
	CoveragePercent float64 `json:"coverage_percent"`
	OldestUnembedded string `json:"oldest_unembedded"`
}

type ExportResult struct {
	Namespace string `json:"namespace"`
	Format string `json:"format"`
	Bytes int `json:"bytes"`
}

type ForgetResult struct {
	Id string `json:"id"`
	Namespace string `json:"namespace"`
	Deleted bool `json:"deleted"`
}

type HealResult struct {
	NamespacesHealed json.RawMessage `json:"namespaces_healed"`
	OrphansDropped int `json:"orphans_dropped"`
}

type ImportResult struct {
	Imported int `json:"imported"`
	Skipped int `json:"skipped"`
	Namespaces json.RawMessage `json:"namespaces"`
}

type IndexResult struct {
	Path string `json:"path"`
	Bytes int `json:"bytes"`
}

type LogResult struct {
	Path string `json:"path"`
	Lines json.RawMessage `json:"lines"`
	Bytes int `json:"bytes"`
}

type McpServeResult struct {
	Status string `json:"status"`
}

type McpToolDescriptor struct {
	Name string `json:"name"`
	Description string `json:"description"`
	InputSchema json.RawMessage `json:"input_schema"`
}

type Memory struct {
	Id string `json:"id"`
	Type string `json:"type"`
	Content string `json:"content"`
	Tags string `json:"tags"`
	Source string `json:"source"`
	Namespace string `json:"namespace"`
	CreatedAt string `json:"created_at"`
	Hash string `json:"hash"`
}

type MemoryAutomation struct {
	Name string `json:"name"`
	Schedule string `json:"schedule"`
	Enabled bool `json:"enabled"`
	Locked bool `json:"locked"`
	LastRun string `json:"last_run"`
	NextRun string `json:"next_run"`
	LogPath string `json:"log_path"`
}

type MemorySearchResult struct {
	Id string `json:"id"`
	Type string `json:"type"`
	Content string `json:"content"`
	Tags string `json:"tags"`
	Source string `json:"source"`
	Namespace string `json:"namespace"`
	CreatedAt string `json:"created_at"`
	Hash string `json:"hash"`
	MatchType string `json:"match_type"`
	Score float64 `json:"score"`
	Distance float64 `json:"distance"`
}

type MoveResult struct {
	From string `json:"from"`
	To string `json:"to"`
	Moved int `json:"moved"`
}

type NamespaceDiff struct {
	Namespace string `json:"namespace"`
	Window string `json:"window"`
	Added int `json:"added"`
	ByType json.RawMessage `json:"by_type"`
	NewMemories json.RawMessage `json:"new_memories"`
}

type NamespaceInfo struct {
	Namespace string `json:"namespace"`
	Count int `json:"count"`
}

type NamespaceStats struct {
	Namespace string `json:"namespace"`
	Total int `json:"total"`
	AtomicCount int `json:"atomic_count"`
	CompiledCount int `json:"compiled_count"`
	ByType json.RawMessage `json:"by_type"`
	Oldest string `json:"oldest"`
	Newest string `json:"newest"`
	LastCompiled string `json:"last_compiled"`
	StaleActionItems json.RawMessage `json:"stale_action_items"`
	NeedsCompilation bool `json:"needs_compilation"`
	UnembeddedCount int `json:"unembedded_count"`
}

type NextRun struct {
	Type string `json:"type"`
	Name string `json:"name"`
	At string `json:"at"`
	CronExpr string `json:"cron_expr"`
}

type RebuildResult struct {
	Namespace string `json:"namespace"`
	Dropped int `json:"dropped"`
	Rebuilt int `json:"rebuilt"`
}

type RenameResult struct {
	From string `json:"from"`
	To string `json:"to"`
	Moved int `json:"moved"`
}

type RestoreResult struct {
	Namespace string `json:"namespace"`
	Restored int `json:"restored"`
}

type SaveMemoryResult struct {
	Id string `json:"id"`
	Namespace string `json:"namespace"`
	Saved bool `json:"saved"`
	Rotated int `json:"rotated"`
}

type ScheduleDisableResult struct {
	Name string `json:"name"`
	Platform string `json:"platform"`
	Success bool `json:"success"`
}

type ScheduleEnableResult struct {
	Name string `json:"name"`
	Platform string `json:"platform"`
	Success bool `json:"success"`
}

type ScheduleEntry struct {
	Type string `json:"type"`
	Name string `json:"name"`
	Platform string `json:"platform"`
	ScheduleLabel string `json:"schedule_label"`
	CronExpr string `json:"cron_expr"`
	Enabled bool `json:"enabled"`
	NextRun string `json:"next_run"`
}

type SqlRow struct {
	Row json.RawMessage `json:"row"`
}

type StaleMemory struct {
	Id string `json:"id"`
	Namespace string `json:"namespace"`
	Type string `json:"type"`
	Content string `json:"content"`
	CreatedAt string `json:"created_at"`
	AgeDays int `json:"age_days"`
}

type TagPattern struct {
	Tag string `json:"tag"`
	Namespaces json.RawMessage `json:"namespaces"`
	Count int `json:"count"`
}

type VacuumResult struct {
	Namespaces json.RawMessage `json:"namespaces"`
	BytesSaved int `json:"bytes_saved"`
}
