// Copyright 2026 abhijit-karode. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCustomAutomationCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "custom-automation",
		Short: "Create, manage, and schedule user-defined automations (agent CLI prompt + cron, configured via LB_AGENT_CLI)",
	}

	cmd.AddCommand(newCustomAutomationCreateCmd(flags))
	cmd.AddCommand(newCustomAutomationDeleteCmd(flags))
	cmd.AddCommand(newCustomAutomationListCmd(flags))
	cmd.AddCommand(newCustomAutomationLogsCmd(flags))
	cmd.AddCommand(newCustomAutomationRunNowCmd(flags))
	cmd.AddCommand(newCustomAutomationStateCmd(flags))
	cmd.AddCommand(newCustomAutomationUpdateCmd(flags))
	return cmd
}
