// Copyright 2026 abhijit-karode. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newEmbeddingsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "embeddings",
		Short: "Manage sqlite-vec embeddings — backfill, coverage, recovery",
	}

	cmd.AddCommand(newEmbeddingsBackfillCmd(flags))
	cmd.AddCommand(newEmbeddingsCheckDepsCmd(flags))
	cmd.AddCommand(newEmbeddingsHealShadowTablesCmd(flags))
	cmd.AddCommand(newEmbeddingsRebuildCmd(flags))
	cmd.AddCommand(newEmbeddingsStatusCmd(flags))
	return cmd
}
