// Copyright 2026 abhijit-karode. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newIndexCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "index",
		Short: "Local Brain index (table-of-contents) operations",
	}

	cmd.AddCommand(newIndexRebuildCmd(flags))
	cmd.AddCommand(newIndexShowCmd(flags))
	return cmd
}
