// Copyright 2026 abhijit-karode. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newMemoryCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "memory",
		Short: "Save, search, recall, and curate typed memories in ~/.local-brain/<namespace>/memories.db",
	}

	cmd.AddCommand(newMemoryBisectCmd(flags))
	cmd.AddCommand(newMemoryContextCmd(flags))
	cmd.AddCommand(newMemoryDedupeCmd(flags))
	cmd.AddCommand(newMemoryExportCmd(flags))
	cmd.AddCommand(newMemoryForgetCmd(flags))
	cmd.AddCommand(newMemoryGetCmd(flags))
	cmd.AddCommand(newMemoryImportCmd(flags))
	cmd.AddCommand(newMemoryListCmd(flags))
	cmd.AddCommand(newMemoryPatternsCmd(flags))
	cmd.AddCommand(newMemorySaveCmd(flags))
	cmd.AddCommand(newMemorySearchCmd(flags))
	cmd.AddCommand(newMemoryStaleCmd(flags))
	cmd.AddCommand(newMemoryWatchCmd(flags))
	return cmd
}
