// Copyright 2026 abhijit-karode. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newMemoryAutomationCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "memory-automation",
		Short: "The 9 bundled memory automations (embedder, indexer, compiler, linter, enricher, pruner, rollup, exporter,...",
	}

	cmd.AddCommand(newMemoryAutomationDisableCmd(flags))
	cmd.AddCommand(newMemoryAutomationEnableCmd(flags))
	cmd.AddCommand(newMemoryAutomationListCmd(flags))
	cmd.AddCommand(newMemoryAutomationLogsCmd(flags))
	cmd.AddCommand(newMemoryAutomationRunNowCmd(flags))
	cmd.AddCommand(newMemoryAutomationStatusCmd(flags))
	return cmd
}
