// Copyright 2026 abhijit-karode. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newNamespaceCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "namespace",
		Short: "Inspect and manage memory namespaces",
	}

	cmd.AddCommand(newNamespaceBackupCmd(flags))
	cmd.AddCommand(newNamespaceDeleteCmd(flags))
	cmd.AddCommand(newNamespaceDiffCmd(flags))
	cmd.AddCommand(newNamespaceListCmd(flags))
	cmd.AddCommand(newNamespaceMoveCmd(flags))
	cmd.AddCommand(newNamespaceRenameCmd(flags))
	cmd.AddCommand(newNamespaceRestoreCmd(flags))
	cmd.AddCommand(newNamespaceStatsCmd(flags))
	cmd.AddCommand(newNamespaceVacuumCmd(flags))
	return cmd
}
