// Copyright 2026 abhijit-karode. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newScheduleCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "schedule",
		Short: "Cross-platform schedule manager — list, install, uninstall, simulate next runs",
	}

	cmd.AddCommand(newScheduleInstallCmd(flags))
	cmd.AddCommand(newScheduleListCmd(flags))
	cmd.AddCommand(newScheduleNextRunsCmd(flags))
	cmd.AddCommand(newScheduleUninstallCmd(flags))
	return cmd
}
